### ISSUE TITLE
Stocker uniquement le nom des fichiers en JavaScript

### ISSUE THREAD

**Issue by oliviermeunier** [kunmanu/slider#3]
Inutile de stocker dans ton tableau le chemin complet vers les fichiers images. Tu peux stocker uniquement le nom de l'image, tu construiras le chemin au moment de changer la source de l'image. Tu peux même stocker ce chemin dans une constante : `const IMAGE_PATH = 'img/'`

![image](https://user-images.githubusercontent.com/5786996/170650236-f12a74a4-7ea4-4f7c-b1d3-08d937b5c8b4.png)

**Comment by kunmanu** [comment]
![image](https://user-images.githubusercontent.com/101394394/170706909-f8b8fe05-a7fb-4e3e-b2b6-4a0a27eeab1e.png)
![image](https://user-images.githubusercontent.com/101394394/170706982-9c776ff8-b570-411a-9e8b-682e320fee76.png)
