### ISSUE TITLE
Gérer le nombre d'images de manière dynamique

### ISSUE THREAD

**Issue by oliviermeunier** [kunmanu/slider#5]
Il vaut mieux gérer le nombre d'images de manière dynamique en utilisant la taille du tableau plutôt que d'écrire le nombre en dur : 

![image](https://user-images.githubusercontent.com/5786996/170650682-2c01e736-9e42-4ff9-9a1c-a00e70f2fc1f.png)

**Comment by kunmanu** [comment]
![image](https://user-images.githubusercontent.com/101394394/170702629-15c6256b-caf2-4014-81b2-1285eb4e35c0.png)

**Comment by kunmanu** [comment]
![image](https://user-images.githubusercontent.com/101394394/170702656-7b71f483-6dd4-4d1d-b076-0621ef24f047.png)
